### ISSUE TITLE
build 22000 and edgedeflector is not working/!!

### ISSUE THREAD

**Issue by yazan1107** [da2x/EdgeDeflector#155] opened 2021-11-30 19:41 UTC
Please follow the troubleshooting steps first!
https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting

**To Reproduce**

**Expected behavior**

**Actual behavior/describe the bug:**
A clear and concise description of what happen instead.

**Details:**
 - Windows version: (Press Win+R, type `winver`, and include the full version number)

**Comment by LorenzoMorelli** [comment] 2021-12-01 10:11
The problem is that EdgeDeflector can be selected as Default (it is not displayed in option menu)

**Comment by yazan1107** [comment] 2021-12-01 10:34
exactly!!

**Comment by cheekoala** [comment] 2021-12-01 15:03
I'm hopping on here to ask if you might have just updated windows 11 to the newest cumulative update, because apparently they're blocking this workaround. (This happened to me)

**Comment by stevenzhu25** [comment] 2021-12-03 19:24
I just tried this on my laptop. 
Windows 11 21H2 (Build 22000.348)
After EdgeDeflector installed, I can find EdgeDeflector by searching on Default Apps search bar, and EdgeDeflector showed up with MS-Edge link option. However, attempting to modify MICROSOFT-EDGE doesn't work because the only app shown in the list is Microsoft Edge (supposed to be Microsoft Edge, Edge Deflector & Search on Microsoft Store)

**Comment by SaphiraKai** [comment] 2021-12-06 02:38
I can confirm this. It used to work until Microshaft decided to block it. I wish I could say I can't believe they've stooped to this point, but no, I can

**Comment by da2x** [comment] 2021-12-08 18:20
Duplicate of #141.

**Closed by da2x** 2021-12-08 18:20 UTC
