### ISSUE TITLE
Edge Deflector is not an option when trying to set "MICROSOFT EDGE" in the app settings

### ISSUE THREAD

**Issue by naossoan** [da2x/EdgeDeflector#163] opened 2021-12-17 03:34 UTC
I'm not able to set Edge Deflector in this setting as the installation instructions say to do.

Thus, it doesn't appear it is working. If I used windows search to do things like I would do on my phone like search for "define "whatever" and it shows me results on the side - clicking any of those links opens Edge, not Chrome.

I have confirmed Chrome is set as default browser.

I have rebooted my machine thinking maybe the installation doesn't complete. Didn't do anything.

I'm not able to choose Edge Deflector in that setting. I'm using Windows 11 on this laptop. In Windows 11 it's also labeled as "Choose defaults by link type"

**Comment by 1Phase1** [comment] 2021-12-17 06:58
Can confirm this same issue on Firefox on Windows 10. Edge Deflector stopped working, so I reinstalled it, and now it doesn't show up in the protocol menu.

**Comment by Jatoxo** [comment] 2021-12-17 22:38
Looks like the last Windows Update broke it? Thanks, Microsoft.

**Comment by RadNotRed** [comment] 2021-12-18 02:36
Does not work on Windows 10 20H1 19043.1415

**Comment by da2x** [comment] 2021-12-18 03:41
Duplicate of #141.

**Closed by da2x** 2021-12-18 03:41 UTC
