### ISSUE TITLE
Doesn't work with Cyrillic (russian) input

### ISSUE THREAD

**Issue by lastblackstone** [da2x/EdgeDeflector#33] opened 2017-10-28 12:39 UTC
When I input russian characters, nothing happens. Nor edge nor chrome is not opening.

**Comment by lastblackstone** [comment] 2017-10-28 12:41
Here is debug url

https://github.com/#microsoft-edge:?launchContext1=Microsoft.Windows.Cortana_cw5n1h2txyewy&url=https%3A%2F%2Fwww.bing.com%2Fsearch%3Fq%3D%25D0%25BF%25D1%2580%25D0%25BE%25D1%2588%25D0%25B8%25D0%25B2%25D0%25BA%25D0%25B0%26form%3DWNSGPH%26qs%3DSW%26cvid%3D3995b5568e964fa28ef75b2b4116a01c%26pq%3D%25D0%25BF%25D1%2580%25D0%25BE%25D1%2588%25D0%25B8%25D0%25B2%25D0%25BA%25D0%25B0%26cc%3DUS%26setlang%3Den-US%26nclid%3DDE5AB82CBDB9C3BA75126551C4E1DF9B%26ts%3D1509194436234%26nclidts%3D1509194436%26tsms%3D234?%3flaunchContext1%3dMicrosoft.Windows.Cortana_cw5n1h2txyewy%26url%3dhttps%253A%252F%252Fwww.bing.com%252Fsearch%253Fq%253D%2525D0%2525BF%2525D1%252580%2525D0%2525BE%2525D1%252588%2525D0%2525B8%2525D0%2525B2%2525D0%2525BA%2525D0%2525B0%2526form%253DWNSGPH%2526qs%253DSW%2526cvid%253D3995b5568e964fa28ef75b2b4116a01c%2526pq%253D%2525D0%2525BF%2525D1%252580%2525D0%2525BE%2525D1%252588%2525D0%2525B8%2525D0%2525B2%2525D0%2525BA%2525D0%2525B0%2526cc%253DUS%2526setlang%253Den-US%2526nclid%253DDE5AB82CBDB9C3BA75126551C4E1DF9B%2526ts%253D1509194436234%2526nclidts%253D1509194436%2526tsms%253D234

**Comment by da2x** [comment] 2017-10-28 13:40
This is a duplicate of issue #32.

Thank you for submitting the debug URL! It really helped in verifying the issue. Expect a new version with a fix early next week. Follow issue #32 for updates.

**Closed by da2x** 2017-10-28 13:40 UTC

**Comment by da2x** [comment] 2017-10-31 22:46
Fixed in version [1.1.2.0](https://github.com/da2x/EdgeDeflector/releases/tag/v1.1.2.0).
