### ISSUE TITLE
Not Opening Chrome

### ISSUE THREAD

**Issue by hennessyp** [da2x/EdgeDeflector#50] opened 2018-01-17 23:24 UTC
I'm having the same problem as others have had in the past (https://github.com/da2x/EdgeDeflector/issues/40). I've got the latest version installed (1.1.3.0) and running https://example.com and microsoft-edge:https://example.com both open the example page in Chrome. However like BurgP7's past problem, when I search in Cortana I get a loading pinwheel next to the cursor, and then nothing happens. How can I fix this?

**Comment by da2x** [comment] 2018-01-18 09:07
Duplicate of #46.

**Closed by da2x** 2018-01-18 09:07 UTC
Labels: duplicate
