### ISSUE TITLE
Edge deflector breaks on Windows 10 after installing update KB5008212 (Cumulative Update for Windows 10 Version 21H1)

### ISSUE THREAD

**Issue by MuellerMarvin** [da2x/EdgeDeflector#158] opened 2021-12-15 03:25 UTC
I have installed this update and noticed that my links now open with edge.
I reinstalled Edge deflector multiple times, hoping that the new release might solve the problem.
Edge deflector did not show up in the protocols list anymore.

Upon manually *uninstalling* this specific windows update, it worked again as usual.
![EvilUpdate](https://user-images.githubusercontent.com/8641639/146117538-ea2ece62-913d-49c1-9ccd-6203dca70c3c.png)
Upon again installing the update, after a restart, functionality ceised again, and edge deflector disappeared from the list of programs once again. 

I see no way of fixing this, is this another Microsoft block, a bug - or my own mistake ?

**Details:**
 - Windows version: 21H1 (Build 19043.1415)

**Comment by da2x** [comment] 2021-12-15 17:32
Duplicate of #141.

**Closed by da2x** 2021-12-15 17:32 UTC

**Comment by MuellerMarvin** [comment] 2021-12-15 22:22
Sorry, thought it was not a duplicate, as this concerns Windows 10, not Windows 11 and it might be a different kind of "block".
😅
