### ISSUE TITLE
Used before,  but doesn't work since new update

### ISSUE THREAD

**Issue by eSleepy** [da2x/EdgeDeflector#48] opened 2017-12-28 23:14 UTC
I used this before, but since the new update it doesn't change anything.  Asks the right questions, but Cortana doesn't really care and uses bing and edge to deliver results.

**Comment by da2x** [comment] 2017-12-29 01:11
Have you installed the [latest version of EdgeDeflector](https://github.com/da2x/EdgeDeflector/releases/latest)? What is your full Windows version (press Win key+R, type winver, and press Enter)? Is the  “Optimize taskbar web search results for screen readers” option enabled in Microsoft Edge: Settings: View advanced settings?

 > Optimize taskbar web search results for screen readers and i switched it off.

**Comment by eSleepy** [comment] 2017-12-29 18:26
Yes Sir, I have the latest version installed.
Windows 10 version 1709 OS build 16299.125 
I went and found everything that I could in MS Edge regarding this and turned it off.  I did not find the exact statement that you have here, but I did find one regarding "Have Cortana assist me in MS Edge".  It was enabled and I turned it off.  Results are still the same at this point.  I'll try a reboot as well.

Thanks for your assistance.

**Comment by eSleepy** [comment] 2017-12-29 18:31
Yes Sir, I have the latest version installed.
Windows 10 version 1709 OS build 16299.125 
I went and found everything that I could in MS Edge regarding this and turned it off.  I did not find the exact statement that you have here, but I did find one regarding "Have Cortana assist me in MS Edge".  It was enabled and I turned it off.  Results are still the same at this point.  I'll try a reboot as well.

Thanks for your assistance.

**Comment by eSleepy** [comment] 2017-12-29 18:32
I installed bing2google in Firefox and at least if I click on something it comes up correctly.  However, it still shows preliminary information in "bing".  Don't know if that just stays the same or not.

Thanks!

**Comment by da2x** [comment] 2018-01-18 09:06
Duplicate of #46.

**Closed by da2x** 2018-01-18 09:06 UTC
