### ISSUE TITLE
It seems that it doesn't work with Chinese input

### ISSUE THREAD

**Issue by ZhangTianrong** [da2x/EdgeDeflector#32] opened 2017-10-27 12:18 UTC
When I talk to Cortana in English , everything goes perfectly, but if I speak Chinese or input Chinese characters, nothing happened literally. No new windows at all, not even Edge.

**Comment by da2x** [comment] 2017-10-27 14:26
Please help me debug the problem further. Which of these work and which doesn’t?

* test 汉语
* 汉语
* test

**Comment by da2x** [comment] 2017-10-27 17:42
Here is a special debug version you can run to collect the information I need to fix this. Unzip it, right-click on the .exe and run it as administrator once (nothing should happen). After doing this, you  can reproduce the problem by searching in Cortana as normal. This will open a special URL on GitHub. Send me this URL and I should have what I need to fix this. Thank you for reporting the issue and thanks for the help.

[EdgeDeflector_uri_debug.zip](https://github.com/da2x/EdgeDeflector/files/1422933/EdgeDeflector_uri_debug.zip)

**Comment by ZhangTianrong** [comment] 2017-10-27 19:40
As long as there's Chinese characters, it fails to work properly. (So it means both "test 汉语" and "汉语".) The URL is [https://github.com/#microsoft-edge:?launchContext1=Microsoft.Windows.Cortana_cw5n1h2txyewy&url=https%3A%2F%2Fcn.bing.com%2Fsearch%3Fq%3D%25E4%25BD%2595%25E4%25BA%258B%25E9%2595%25BF%25E5%2590%2591%25E5%2588%25AB%25E6%2597%25B6%25E5%259C%2586%26form%3DWNSGPH%26qs%3DSW%26cvid%3Dc3a7dc5030eb43509471b9cd0133c996%26pq%3D%25E4%25BD%2595%25E4%25BA%258B%25E9%2595%25BF%25E5%2590%2591%25E5%2588%25AB%25E6%2597%25B6%25E5%259C%2586%26cc%3DCN%26setlang%3Dzh-Hans-CN%26nclid%3DCBD7F5A706969F81452256E2A0FD8A7A%26ts%3D1509133046730%26nclidts%3D1509133046%26tsms%3D730?%3flaunchContext1%3dMicrosoft.Windows.Cortana_cw5n1h2txyewy%26url%3dhttps%253A%252F%252Fcn.bing.com%252Fsearch%253Fq%253D%2525E4%2525BD%252595%2525E4%2525BA%25258B%2525E9%252595%2525BF%2525E5%252590%252591%2525E5%252588%2525AB%2525E6%252597%2525B6%2525E5%25259C%252586%2526form%253DWNSGPH%2526qs%253DSW%2526cvid%253Dc3a7dc5030eb43509471b9cd0133c996%2526pq%253D%2525E4%2525BD%252595%2525E4%2525BA%25258B%2525E9%252595%2525BF%2525E5%252590%252591%2525E5%252588%2525AB%2525E6%252597%2525B6%2525E5%25259C%252586%2526cc%253DCN%2526setlang%253Dzh-Hans-CN%2526nclid%253DCBD7F5A706969F81452256E2A0FD8A7A%2526ts%253D1509133046730%2526nclidts%253D1509133046%2526tsms%253D730](url).

**Comment by da2x** [comment] 2017-10-28 13:38
Thank you. It's caused by a bug in Windows where the query portion of the URL is duplicated. (Don't they do any quality control at Microsoft!?) I can work around the issue and prepare a patch and release a new version early next week. Thank you for the help in identifying the issue!

**Comment by da2x** [comment] 2017-10-31 22:46
Fixed in version [1.1.2.0](https://github.com/da2x/EdgeDeflector/releases/tag/v1.1.2.0).

**Closed by da2x** 2017-10-31 22:46 UTC
