### ISSUE TITLE
EdgeDeflector stopped working.

### ISSUE THREAD

**Issue by szpatrik5** [da2x/EdgeDeflector#164] opened 2021-12-18 20:42 UTC
Please follow the troubleshooting steps first!
https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting

**To Reproduce**
1. Try to open a link with MICROSOFT-EDGE
or
1. Go to choose default apps by protocol.
2. Locate MICROSOFT-EDGE in the list and click on the program icon.
3. EdgeDeflector not on the list.

**Expected behavior**
Opens your default browser with the link.

**Actual behavior/describe the bug:**
Opens Edge with the link. 

**Details:**
 - Windows version: Windows 10 Pro 21h2

**Comment by Thespikedballofdoom** [comment] 2021-12-18 21:25
Same

**Comment by da2x** [comment] 2021-12-19 01:04
Duplicate of #141.

**Closed by da2x** 2021-12-19 01:04 UTC
