### ISSUE TITLE
Release 1.1.3.0 does not work

### ISSUE THREAD

**Issue by Farix1337** [da2x/EdgeDeflector#54] opened 2018-03-15 08:10 UTC
The newest released Version 1.1.3.0 does not work. Web requests in the search bar will do completly nothing and the edgedeflector process does not start at all. The previous version do run fine.
When i tried the version in the issue before me it worked too, but redirected me to github all the time.
Windows-Specifications: Windows 10 Pro Version 1709 Build 16299.309

**Comment by yamnakshatriya** [comment] 2018-03-25 17:12
Same problem - working with Firefox, simply nothing happens.

**Comment by mr-coetzee** [comment] 2018-03-29 13:22
Thank you for the solution, but regrettably it does not work.

**Comment by Shadesss** [comment] 2018-04-14 16:56
New user, just learned of edge deflector and not working for me either.

**Comment by da2x** [comment] 2018-05-03 19:10
Duplicate of issue #52.

**Closed by da2x** 2018-05-03 19:10 UTC
