### ISSUE TITLE
Doesn't work on 21H2

### ISSUE THREAD

**Issue by WeedCandy** [da2x/EdgeDeflector#159] opened 2021-12-15 17:30 UTC
Please follow the troubleshooting steps first!
https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting

**To Reproduce**
Install it. Doesn't show the default app popup as normal. EdgeDeflector isn't shown in the list. Same behavior when clicking on a link on the lock screen.

**Details:**
 - Windows version: (Press Win+R, type `winver`, and include the full version number)
21H2

**Comment by da2x** [comment] 2021-12-15 17:32
Duplicate of #141.

**Comment by WeedCandy** [comment] 2021-12-15 17:33
Not a duplicate. This is Windows 10.

**Closed by da2x** 2021-12-15 17:32 UTC

**Comment by da2x** [comment] 2021-12-15 17:33
It’s the same underlying issue.

**Comment by WeedCandy** [comment] 2021-12-15 17:34
Ok thanks! And thank you for providing EdgeDeflector.
