### ISSUE TITLE
It's broken for me

### ISSUE THREAD

**Issue by Zaannaah** [da2x/EdgeDeflector#49] opened 2018-01-17 06:12 UTC
I'm not sure if windows has had an update since the rest of these guys commented but just a heads up. This is not working for me on a freshly installed and updated copy of windows 10 pro version 1709 build 16299.192. also thank you for the work you're doing here this workaround is a life saver

**Comment by da2x** [comment] 2018-01-18 09:06
Duplicate of #46.

**Closed by da2x** 2018-01-18 09:06 UTC
Labels: duplicate
