### ISSUE TITLE
Not working after KB5007262

### ISSUE THREAD

**Issue by sinand99** [da2x/EdgeDeflector#152] opened 2021-11-23 16:32 UTC
It doesn't work any more on Windows 11 OS Build 22000.348 after installing update KB5007262. I think it is because ms-edge link name changed to microsoft-edge.

**Comment by tkodev** [comment] 2021-11-24 02:11
Duplicate of https://github.com/da2x/EdgeDeflector/issues/141

**Comment by da2x** [comment] 2021-11-26 04:23
Duplicate of #141.

**Closed by da2x** 2021-11-26 04:23 UTC
