### ISSUE TITLE
cannot change to Edge Deflector on default applications by protocol

### ISSUE THREAD

**Issue by dtantono** [da2x/EdgeDeflector#151] opened 2021-11-23 05:35 UTC
Please follow the troubleshooting steps first!
https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting

**To Reproduce**
1. Go to https://github.com/da2x/EdgeDeflector/releases/tag/v1.2.3.0
2. Click on Setting
3. Click on Apps
4. go to  default apps
5. scroll down to default applications by protocol
6. Find MICROSOFT-EDGE
7. I cannot change to default applications by protocol

**Expected behavior**
I cannot change to default applications by protocol

**Actual behavior/describe the bug:**
I cannot change to default applications by protocol

**Details:**
 - Windows 10 version 21h2 OS Build 19044.1387
<img width="726" alt="Screenshot 2021-11-23 143018" src="https://user-images.githubusercontent.com/29157187/142975889-7e824ad1-7964-4212-968a-7db761abb445.png">

**Comment by FluffBallFloof** [comment] 2021-11-23 06:00
Same issue for me, also on 21H2.

**Comment by iskandarluqman** [comment] 2021-11-23 12:07
I can confirm that I am having the exact same issue on Windows 10 version 21H2 with OS Build 19044.1387

**Comment by sturdy-cactus** [comment] 2021-11-23 19:05
confirm, same issue.

**Comment by designatedcoder** [comment] 2021-11-24 14:37
Same for me.  I tried resetting everything back to default settings then did a clean install of deflector.  Still won't let me change it.

**Comment by meek2100** [comment] 2021-11-24 21:13
Duplicate of #141?

**Comment by dtantono** [comment] 2021-11-24 23:22
@meek2100 that one is for Win11 and this one is for Win10

**Comment by 1to5pc** [comment] 2021-11-25 14:03
MS is breaking the functionality of this app. :(

**Comment by dtantono** [comment] 2021-11-25 15:51
Since win10 and win11 are not really the same OS. I hope MS does not synergise the win11 policy to win10.

**Comment by 1to5pc** [comment] 2021-11-26 02:54
> 

If they feel want to (there is a high chance they will) they might push the policy to win 10 as well

**Comment by da2x** [comment] 2021-11-26 04:23
Duplicate of #141.

**Closed by da2x** 2021-11-26 04:23 UTC

**Comment by dtantono** [comment] 2021-11-26 04:29
@da2x Windows 11 and Windows 10 is not same OS. Why close it?

**Comment by Briareos-A** [comment] 2022-01-28 23:35
Because #141 has a [solution](https://github.com/da2x/EdgeDeflector/issues/141#issuecomment-997438087) to this problem. 

[MSEdgeRedirect](https://github.com/rcmaehl/MSEdgeRedirect)
