### ISSUE TITLE
Not working in Parallels

### ISSUE THREAD

**Issue by martin-braun** [da2x/EdgeDeflector#157] opened 2021-12-13 21:16 UTC
I try to use EdgeDeflector in a Windows 10 VM with Parallels where the default browser is a short-cut that passes the link through to the host system which is macOS by configuring the VM like so: 

<img width="1053" alt="Screen Shot 2021-12-13 at 22 12 13" src="https://user-images.githubusercontent.com/24259245/145889617-c738b4ed-eff1-4d65-a6e3-48b010ad4758.png">

Using this setting you can share apps of macOS within Windows 10, so you can do this, so links open in Brave on macOS: 

<img width="606" alt="Screen Shot 2021-12-13 at 22 18 22" src="https://user-images.githubusercontent.com/24259245/145890341-8a9d211c-7035-49c4-8d0f-2519089e56d2.png">

Now I try to use EdgeDeflector to do the same with links in the start menu like it already does with any other link successfully, but it doesn't work.

**To Reproduce**
1. Install Windows 10 in Parallels on macOS
2. Share macOS Apps with VM in Parallels settings
3. Install Brave Browser in macOS
4. Select default browser to "Brave Browser (Mac)" in Windows
5. Install EdgeDeflector

**Expected behavior**
Will open links in the default browser which is Brave on the Host system macOS. This works for conventional ways, but not in EdgeDeflector.

**Actual behavior/describe the bug:**
<img width="413" alt="Screen Shot 2021-12-13 at 22 05 44" src="https://user-images.githubusercontent.com/24259245/145888993-4e7067de-1b5b-4425-847f-c1acda0d59b9.png">

This pops up instead. I cannot select "Brave Browser (Mac)"

**Details:**
 - Parallels version: 17.01
 - Windows version: 10 (21H1)

**Some final notes**
I know this is a hard edge case and I have complete understanding if nobody is interested to fix this, since this is not even related to Windows by 100% and it requires Apple hardware to even confirm this issue I have. I also opened this to get some hints how I could fix this, I appreciate any help I get to solve this.

**Comment by mcfalld** [comment] 2021-12-16 01:54
![image](https://user-images.githubusercontent.com/32588824/146293556-9d821284-1903-4a5b-a0b4-194d00f6b526.png)
just downloaded the MSER and unzipped it, installed and still getting the same prompt

**Comment by da2x** [comment] 2022-01-17 13:40
Duplicate of #141.

**Closed by da2x** 2022-01-17 13:40 UTC
