### ISSUE TITLE
Facebook app still opens Edge

### ISSUE THREAD

**Issue by frodrick79** [da2x/EdgeDeflector#137] opened 2021-10-03 11:52 UTC
Windows 10 Ver 20H2 os build 19042. 1237

Installed deflector according to instructions, works as far as opening a link in chrome when pasting in RUN window.
But when it comes to clicking links in Windows Facebook App Ver 2021.927.1.0 it still open links in Edge browser.

**Comment by da2x** [comment] 2021-10-03 12:40
This is a duplicate of issue #134.

**Closed by da2x** 2021-10-03 12:40 UTC
