### ISSUE TITLE
Latest Version of Windows 10 roadblock

### ISSUE THREAD

**Issue by AgnesCarlos** [da2x/EdgeDeflector#173] opened 2022-01-05 10:49 UTC
**To Reproduce**
1. Go to DOWNLOAD LATEST VERSION OF EdgeDeflector
2. Click on INSTALL
3. Scroll down to '....' NA
4. Window asks where to install EdgeDeflector on your computer, an install window appears to pop up for an instant, and is immediately gone.

**Expected behavior**
I expect to install EdgeDeflector on my PC

**Actual behavior/describe the bug:**
It appears EdgeDeflector is attempting to install, but Windows 10 immediately shuts it down - there are no warnings, there appears to be an install window about to load and then it disappears.

**Details:**
 - Windows version: Windows 10 21H1 (OS Build 19043.1415)
Thank you.

**Comment by DaedB** [comment] 2022-01-08 07:04
See #141 . Issue was originally with Windows 11 but now affects the latest version of Windows 10 with the 21H1 update.

**Comment by KirkH420** [comment] 2022-01-09 07:48
I uninstalled the KB500812 update, rebooted, uninstalled/reinstalled EdgeDeflector, and it's back working again. 

I also attempted to hide the update with WuShowHide (the newer signed version) but I'm pretty sure I've already had updates push right past this in recent history, so I guess I'll have to wait and see. I have my Windows Update set to not download anything without asking me, but I think if I don't check on updates from time to time, they'll eventually force them through. 

There is a pretty easy way to stop WU permanently (until you reverse it) but it's a bit of a hacky method. You can locate the \SoftwareDistribution directory and through Properties Security Tab, take ownership of the directory, disable inheritance, then change permissions for the SYSTEM account from "allow" to "deny" (full controls). Also remove all other accounts from this list, leaving only SYSTEM and an Admin account. After this, windows won't be able to write the updates that it tries to download. It's easy to reverse, just run wu170509.diagcab (WU Troubleshoot). It will restore everything back to normal and that way you don't need to remember the various accounts you removed. I use this method all the time without any issues.

These MS bastards really aren't as smart as they think they are. People will just make switching to Linux distros easier and more user friendly for the less tech savvy and users will migrate away from their spy-ware operating system. As it is, I have no desire to move to 11.

**Comment by TheDrawingCoder-Gamer** [comment] 2022-01-09 17:01
protip: you can set your connection to metered to prevent auto downloads

**Comment by da2x** [comment] 2022-01-17 13:39
Duplicate of #141.

**Closed by da2x** 2022-01-17 13:39 UTC
