### ISSUE TITLE
Cannot set EdgeDeflector in Windows 11 Build 22000.346

### ISSUE THREAD

**Issue by dhirenmehta** [da2x/EdgeDeflector#145] opened 2021-11-15 18:32 UTC
Please follow the troubleshooting steps first!
https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting

**To Reproduce**
Have installed as per instructions, followed steps to complete the final 'post-install' steps. I am aware that on the new dev builds, EdgeDeflector is now blocked, but I'm on 22000.346 and do not get the option to select EdgeDeflector as the handling app. 

![image](https://user-images.githubusercontent.com/8790325/141835377-8e3f2d16-1547-4951-bae5-5083cd3ef412.png)

**Expected behavior**
Be able to select EdgeDeflector as final post install step and then test to confirm working. 

**Actual behavior/describe the bug:**
As above

**Details:**
 - Windows version: Windows 11 Pro 22000.346

**Comment by da2x** [comment] 2021-11-15 19:46
I’m assuming this is a duplicate of #141.

**Closed by da2x** 2021-11-15 19:46 UTC
