### ISSUE TITLE
Searching with cortana/windows search no longer redirects to preferred browser

### ISSUE THREAD

**Issue by Earthsam12** [da2x/EdgeDeflector#172] opened 2022-01-03 01:02 UTC
Searching with cortana/windows search no longer redirects to preferred browser; opens "How do you want to open this window" which does not list EdgeDeflector. 

I noticed #141 had this but for Windows 11, this is Windows 10.

**To Reproduce**
1. Open windows search bar
2. Type in anything that will lead to web result
3. Press enter
4. See "How do you want to open this?" Window with **no option to select edge deflector**

**Expected behavior**
Should redirect to preferred browser OR EdgeDeflector should be listed in that window .

**Actual behavior/describe the bug:**
Opens "How do you want to open this"

**Details:**
 - Windows version: 21H1 19043.1415
 - Win+R "https://www.example.com" will redirect normally, "microsoft-edge://example.com/" will not

**Comment by NilsMoller** [comment] 2022-01-03 18:02
Duplicate: https://github.com/da2x/EdgeDeflector/issues/141

**Comment by bMorgan01** [comment] 2022-01-06 22:03
I'm having the same issue on Windows 10

**Comment by thd14** [comment] 2022-01-07 10:23
I have the same issue on Windows 10 Pro

**Comment by WeedCandy** [comment] 2022-01-08 15:18
MSEdgeRedirect works (in service mode only as far as I can tell). I suspect this project is dead.

**Comment by da2x** [comment] 2022-01-17 13:39
Duplicate of #141.

**Closed by da2x** 2022-01-17 13:39 UTC
