### ISSUE TITLE
not working after fall creators update

### ISSUE THREAD

**Issue by misterjupiter** [da2x/EdgeDeflector#30] opened 2017-10-25 16:09 UTC
edge-deflector stopped working after upgrading windows 10 with the fall creators update to v.1709.
Manually setting edge-deflector as standard in System-Settings > Apps > Standard-Apps > By protocol to use edge-deflector for MIRCOSOFT-EDGE doesn't work either.

**Comment by da2x** [comment] 2017-10-25 16:56
Duplicate of issue #/14. Please upgrade to the [latest version](https://github.com/da2x/EdgeDeflector/releases).

**Closed by da2x** 2017-10-25 16:56 UTC
