### ISSUE TITLE
EdgeDeflector no longer an option for microsoft-edge protocol

### ISSUE THREAD

**Issue by cam-rod** [da2x/EdgeDeflector#161] opened 2021-12-16 18:17 UTC
**To Reproduce**
1. Update Windows 10 to version 19041.1415 or later.
2. Click the Windows search bar, and click the Web option at the top
3. Type a query and hit Enter.

**Expected behavior**
The search result or webpage opens in the default browser

**Actual behavior/describe the bug:**
- If EdgeDeflector was previously installed and working before the update, Windows asks to set a default program to open it. 
![Screenshot 2021-12-16 125502](https://user-images.githubusercontent.com/40349712/146425202-c2bf0c83-853d-44b1-b46a-4912341256ca.png)
- If EdgeDeflector was not previously installed, the webpage opens in Microsoft Edge. 
![image](https://user-images.githubusercontent.com/40349712/146425585-fae29c36-4a59-4e10-b1ac-9afd08f50309.png)

**Details:**
 - Previously installed version
   - Windows 10 21H1 (19043.1415)
 - Newly installed version
   - Windows 10 21H1 (19041.1415)
   - Tested in Windows Sandbox

This appears to be the same issue as #157. I suspect an update I installed last night \([KB5008212](https://support.microsoft.com/en-us/topic/december-14-2021-kb5008212-os-builds-19041-1415-19042-1415-19043-1415-and-19044-1415-b46200db-74c3-450e-b200-51013957312a)\) has backported the changes from Windows 11.

**Comment by da2x** [comment] 2021-12-16 18:24
Duplicate of #141.

**Closed by da2x** 2021-12-16 18:24 UTC
