### ISSUE TITLE
Windows 11 Support

### ISSUE THREAD

**Issue by NextdoorPsycho** [da2x/EdgeDeflector#166] opened 2021-12-19 19:26 UTC
Please follow the troubleshooting steps first!
https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting

**To Reproduce**
- Try and install it on windows 11, Windows 11 prevents you from changing the features that cortana has access too:
https://gfycat.com/UnderstatedSameIndianabat 

**Expected behavior**
- Should allow me to modify, does not even show. might need to be a store app

**Actual behavior/describe the bug:**
The program should function in the menus

**Details:**
https://i.imgur.com/gdFpEK0.png

**Comment by marcandrer** [comment] 2021-12-19 21:16
Microsoft is now blocking the use of software like EdgeDeflector.

https://www.theverge.com/2021/11/15/22782802/microsoft-block-edgedeflector-windows-11

**Comment by mazak-ui** [comment] 2021-12-19 21:17
This is a duplicate of #[165](https://github.com/da2x/EdgeDeflector/issues/165)

**Comment by charakaSamawry** [comment] 2021-12-20 00:47
https://github.com/rcmaehl/MSEdgeRedirect 
Is a currently working alternative, and works in Wendoos 11, apparently (still on W10)

**Comment by da2x** [comment] 2021-12-26 17:20
Duplicate of #141.

**Closed by da2x** 2021-12-26 17:20 UTC
