### ISSUE TITLE
I don't have choice default app by protokoll in settings

### ISSUE THREAD

**Issue by Gurra0424** [da2x/EdgeDeflector#168] opened 2021-12-29 15:04 UTC
Please follow the troubleshooting steps first!
https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting

**To Reproduce**
1. Go to "WIN + I"
2. Click on 'Apps'
3. Click on default apps.
3. Scroll down to the bottom

I have the newest public release of windows 11

**Comment by tseterry** [comment] 2022-01-01 22:29
this is occurring in Windows 10 too. On the latest build: 19043.1415

**Comment by da2x** [comment] 2022-01-17 13:40
Duplicate of #141.

**Closed by da2x** 2022-01-17 13:40 UTC
