### ISSUE TITLE
Stopped working after 21H2 installation

### ISSUE THREAD

**Issue by fireton** [da2x/EdgeDeflector#160] opened 2021-12-16 15:31 UTC
**To Reproduce**
1. Install 21H2 update
2. Try open `microsoft-edge://example.com/`
3. Windows asks for application
![image](https://user-images.githubusercontent.com/662637/146399900-eb90025f-8daf-48bf-a5dd-1a7245582ce3.png)
4. No EdgeDeflector in the list and I can't choose it in Preffered Apllications settings.
5. Reinstalling of EdgeDeflector no avail either

**Details:**
 - Windows version: 21H2 (build 19044.1415)

**Comment by Sharknoon** [comment] 2021-12-16 17:29
I have the same problem. EdgeDeflector isn't showing up in the list, after a recent Windows 11 update

**Comment by da2x** [comment] 2021-12-16 17:50
Duplicate of #141.

**Closed by da2x** 2021-12-16 17:50 UTC
